In [83]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Filtering all the AQI Databases from the last 5 years to only include Texas

In [84]:
# 2025
df = pd.read_csv("/content/annual_aqi_by_county_2025.csv")
texasAQI_25 = df[df["State"] == "Texas"]
print(texasAQI_25.shape)
texasAQI_25.head(10)

(45, 18)

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10
798,Texas,Atascosa,2025,341,259,82,0,0,0,0,92,61,35,0,0,0,341,0
799,Texas,Bell,2025,365,241,120,4,0,0,0,140,65,45,0,0,236,129,0
800,Texas,Bexar,2025,365,158,196,10,1,0,0,154,80,52,0,4,152,203,6
801,Texas,Bowie,2025,342,188,153,1,0,0,0,107,59,48,0,0,0,342,0
802,Texas,Brazoria,2025,365,295,62,8,0,0,0,143,71,35,0,11,326,28,0
803,Texas,Brazos,2025,340,233,107,0,0,0,0,78,57,40,0,0,0,340,0
804,Texas,Brewster,2025,364,272,91,0,1,0,0,164,64,43,0,0,307,57,0
805,Texas,Cameron,2025,365,109,248,8,0,0,0,139,76,57,0,0,50,315,0
806,Texas,Collin,2025,359,272,64,20,3,0,0,156,90,40,0,0,359,0,0
807,Texas,Culberson,2025,88,67,19,1,1,0,0,159,67,32,0,0,0,88,0

In [85]:
# 2024
df = pd.read_csv("/content/annual_aqi_by_county_2024.csv")
texasAQI_24 = df[df["State"] == "Texas"]
print(texasAQI_24.shape)
texasAQI_24.head(10)

(45, 18)

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10
808,Texas,Atascosa,2024,347,198,141,8,0,0,0,116,72,44,0,0,0,347,0
809,Texas,Bell,2024,366,226,135,5,0,0,0,129,70,46,0,0,224,142,0
810,Texas,Bexar,2024,366,174,170,20,2,0,0,199,87,52,0,3,139,221,3
811,Texas,Bowie,2024,360,189,171,0,0,0,0,97,62,49,0,0,0,360,0
812,Texas,Brazoria,2024,365,303,56,5,1,0,0,164,60,37,0,4,330,31,0
813,Texas,Brazos,2024,353,232,120,1,0,0,0,102,58,39,0,0,0,353,0
814,Texas,Brewster,2024,327,231,94,2,0,0,0,112,67,43,0,0,241,86,0
815,Texas,Cameron,2024,366,99,206,48,13,0,0,171,124,61,0,0,44,322,0
816,Texas,Collin,2024,365,283,71,8,3,0,0,161,77,40,0,0,365,0,0
817,Texas,Culberson,2024,111,99,12,0,0,0,0,88,52,26,0,0,0,111,0

In [86]:
# 2023
df = pd.read_csv("/content/annual_aqi_by_county_2023.csv")
texasAQI_23 = df[df["State"] == "Texas"]
print(texasAQI_23.shape)
texasAQI_23.head(10)

(45, 18)

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10
806,Texas,Atascosa,2023,330,210,120,0,0,0,0,86,64,42,0,0,0,330,0
807,Texas,Bell,2023,365,231,128,6,0,0,0,133,74,44,0,0,246,119,0
808,Texas,Bexar,2023,365,164,189,10,1,0,1,309,79,52,0,1,141,223,0
809,Texas,Bowie,2023,321,130,190,1,0,0,0,107,65,53,0,0,0,321,0
810,Texas,Brazoria,2023,365,301,47,16,1,0,0,156,67,36,0,7,336,22,0
811,Texas,Brazos,2023,348,233,115,0,0,0,0,79,60,39,0,0,0,348,0
812,Texas,Brewster,2023,359,262,96,1,0,0,0,101,58,43,0,0,228,131,0
813,Texas,Cameron,2023,365,161,198,6,0,0,0,141,77,54,0,0,103,262,0
814,Texas,Collin,2023,356,261,74,19,2,0,0,154,80,41,0,0,356,0,0
815,Texas,Culberson,2023,107,101,6,0,0,0,0,89,44,20,0,0,0,107,0

In [87]:
# 2022
df = pd.read_csv("/content/annual_aqi_by_county_2022.csv")
texasAQI_22 = df[df["State"] == "Texas"]
print(texasAQI_22.shape)
texasAQI_23.head(10)

(45, 18)

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10
806,Texas,Atascosa,2023,330,210,120,0,0,0,0,86,64,42,0,0,0,330,0
807,Texas,Bell,2023,365,231,128,6,0,0,0,133,74,44,0,0,246,119,0
808,Texas,Bexar,2023,365,164,189,10,1,0,1,309,79,52,0,1,141,223,0
809,Texas,Bowie,2023,321,130,190,1,0,0,0,107,65,53,0,0,0,321,0
810,Texas,Brazoria,2023,365,301,47,16,1,0,0,156,67,36,0,7,336,22,0
811,Texas,Brazos,2023,348,233,115,0,0,0,0,79,60,39,0,0,0,348,0
812,Texas,Brewster,2023,359,262,96,1,0,0,0,101,58,43,0,0,228,131,0
813,Texas,Cameron,2023,365,161,198,6,0,0,0,141,77,54,0,0,103,262,0
814,Texas,Collin,2023,356,261,74,19,2,0,0,154,80,41,0,0,356,0,0
815,Texas,Culberson,2023,107,101,6,0,0,0,0,89,44,20,0,0,0,107,0

In [88]:
# 2021
df = pd.read_csv("/content/annual_aqi_by_county_2021.csv")
texasAQI_21 = df[df["State"] == "Texas"]
print(texasAQI_21.shape)
texasAQI_21.head(10)

(45, 18)

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10
815,Texas,Atascosa,2021,356,213,143,0,0,0,0,87,63,43,0,0,0,356,0
816,Texas,Bell,2021,365,240,122,3,0,0,0,122,69,44,0,0,230,135,0
817,Texas,Bexar,2021,365,113,240,12,0,0,0,147,80,55,0,0,94,269,2
818,Texas,Bowie,2021,357,163,193,1,0,0,0,106,64,52,0,0,0,357,0
819,Texas,Brazoria,2021,365,331,22,11,1,0,0,159,50,34,0,10,355,0,0
820,Texas,Brazos,2021,356,248,108,0,0,0,0,85,58,40,0,0,0,356,0
821,Texas,Brewster,2021,356,287,68,1,0,0,0,105,57,42,0,0,276,80,0
822,Texas,Cameron,2021,365,162,203,0,0,0,0,99,70,52,0,0,67,298,0
823,Texas,Collin,2021,357,294,55,7,1,0,0,154,64,37,0,0,357,0,0
824,Texas,Culberson,2021,221,170,47,4,0,0,0,126,64,43,0,0,145,76,0

Combining seperate years of AQI data into one dataset with all 5 years

In [89]:
# code for combining aqi data

AQI = pd.concat([texasAQI_21, texasAQI_22, texasAQI_23, texasAQI_24, texasAQI_25])
print(df12.shape)
AQI['Year'].value_counts()

(225, 18)

Year
2021    45
2022    45
2023    45
2024    45
2025    45
Name: count, dtype: int64

Loading all the Temperature data from the last 5 years (only includes Texas Counties)

Creating the Temperature dataset

In [90]:
Temperature25 = pd.read_csv("/content/avg_temps_2025.csv", header=2, skiprows=[2])
Temperature25.rename(columns={"Name": "County"}, inplace=True)
Temperature25['Year'] = 2025
print(Temperature25.shape)
#print(Temperature25.head())


Temperature24 = pd.read_csv("/content/avg_temps_2024.csv", header=2, skiprows=[2])
Temperature24.rename(columns={"Name": "County"}, inplace=True)
Temperature24['Year'] = 2024
print(Temperature24.shape)
#print(Temperature24.head())

Temperature23 = pd.read_csv("/content/avg_temps_2023.csv", header=2, skiprows=[2])
Temperature23.rename(columns={"Name": "County"}, inplace=True)
Temperature23['Year'] = 2023
print(Temperature23.shape)
#print(Temperature23.head())

Temperature22 = pd.read_csv("/content/avg_temps_2022.csv", header=2, skiprows=[2])
Temperature22.rename(columns={"Name": "County"}, inplace=True)
Temperature22['Year'] = 2022
print(Temperature22.shape)
#print(Temperature22.head())

Temperature21 = pd.read_csv("/content/avg_temps_2021.csv", header=2, skiprows=[2])
Temperature21.rename(columns={"Name": "County"}, inplace=True)
Temperature21['Year'] = 2021
print(Temperature21.shape)
#print(Temperature21.head())

Temperature = pd.concat([Temperature21, Temperature22, Temperature23, Temperature24, Temperature25])
Temperature['County'].value_counts()
#Temperature.columns

(254, 8)
(254, 8)
(254, 8)
(254, 8)
(254, 8)

County
Anderson County    5
Andrews County     5
Angelina County    5
Aransas County     5
Archer County      5
                  ..
Wood County        5
Yoakum County      5
Young County       5
Zapata County      5
Zavala County      5
Name: count, Length: 254, dtype: int64

In [113]:
AggTemp = Temperature.groupby('County')['Value'].agg(
    Mean='mean',
    Median='median',
    STD='std',
    Min='min',
    Max='max'
).reset_index()

AggTemp.rename(columns = {
    'Mean': 'Mean_Temp',
    'Median': 'Median_Temp',
    'STD': 'STD_Temp',
    'Min': 'Min_Temp',
    'Max': 'Max_Temp'
}, inplace = True)
AggTemp.rename(columns={'County': 'Name'}, inplace=True)
AggTemp['Mean_Temp'].round(2)
display(AggTemp)

                Name  Mean_Temp  Median_Temp  STD_Temp  Min_Temp  Max_Temp
0    Anderson County      67.22         67.7  0.872926      66.0      68.0
1     Andrews County      64.92         65.5  1.279453      63.4      66.2
2    Angelina County      68.52         68.5  0.746324      67.8      69.5
3     Aransas County      73.70         74.1  1.067708      72.3      74.9
4      Archer County      65.86         65.8  1.145862      64.3      67.2
..               ...        ...          ...       ...       ...       ...
249      Wood County      65.86         66.0  1.080740      64.4      67.1
250    Yoakum County      61.76         62.1  1.047855      60.5      62.7
251     Young County      65.92         66.1  1.296919      64.1      67.3
252    Zapata County      76.02         76.2  1.127830      74.6      77.4
253    Zavala County      72.94         73.4  1.130487      71.6      74.2

[254 rows x 6 columns]

In [116]:
AggTemp.to_csv("Temperature_Aggregation.csv")

Keeping only relevant features (after combining all the datasets together)

In [95]:
keep = []