In [ ]:
import pandas as pd

In [ ]:
one = pd.read_csv('avg_rains_2021.csv', header = 2, skiprows = [2])
two = pd.read_csv('avg_rains_2022.csv', header = 2, skiprows = [2])
three = pd.read_csv('avg_rains_2023.csv', header = 2, skiprows = [2])
four = pd.read_csv('avg_rains_2024.csv', header = 2, skiprows = [2])
five = pd.read_csv('avg_rains_2025.csv', header = 2, skiprows = [2])
rains = pd.concat([one, two, three, four, five])
rains

,ID,Name,State,Value,Anomaly (1901-2000 base period),Rank,1901-2000 Mean,Pctavg,Percent of Average
0,TX-001,Anderson County,Texas,46.46,4.90,95,41.56,111.8,NaN
1,TX-003,Andrews County,Texas,13.14,-1.52,53,14.66,89.6,NaN
2,TX-005,Angelina County,Texas,54.38,5.78,96,48.60,111.9,NaN
3,TX-007,Aransas County,Texas,54.46,20.71,130,33.75,161.4,NaN
4,TX-009,Archer County,Texas,25.93,-1.75,54,27.68,93.7,NaN
...,...,...,...,...,...,...,...,...,...
249,TX-499,Wood County,Texas,45.95,3.53,86,42.42,108.3,NaN
250,TX-501,Yoakum County,Texas,14.26,-2.53,44,16.79,85.0,NaN
251,TX-503,Young County,Texas,32.91,5.21,99,27.70,118.8,NaN
252,TX-505,Zapata County,Texas,13.44,-5.45,15,18.89,71.1,NaN
253,TX-507,Zavala County,Texas,16.62,-5.55,32,22.17,75.0,NaN

In [ ]:
sorted_rain = rains.sort_values(by = ['Name'])
sorted_rain

,ID,Name,State,Value,Anomaly (1901-2000 base period),Rank,1901-2000 Mean,Pctavg,Percent of Average
0,TX-001,Anderson County,Texas,46.46,4.90,95,41.56,111.8,NaN
0,TX-001,Anderson County,Texas,37.96,-3.60,46,41.56,91.3,NaN
0,TX-001,Anderson County,Texas,62.36,20.80,129,41.56,150.0,NaN
0,TX-001,Anderson County,Texas,35.32,-6.24,34,41.56,85.0,NaN
0,TX-001,Anderson County,Texas,45.23,3.67,84,41.56,108.8,NaN
...,...,...,...,...,...,...,...,...,...
253,TX-507,Zavala County,Texas,14.51,-7.66,15,22.17,65.4,NaN
253,TX-507,Zavala County,Texas,16.77,-5.40,34,22.17,75.6,NaN
253,TX-507,Zavala County,Texas,22.48,0.31,75,22.17,101.4,NaN
253,TX-507,Zavala County,Texas,15.71,-6.46,24,22.17,70.9,NaN
253,TX-507,Zavala County,Texas,16.62,-5.55,32,22.17,75.0,NaN

In [ ]:
AggRain = pd.DataFrame()
AggRain = sorted_rain.groupby('Name')['Value'].mean().reset_index(name = 'Mean_Rain')
std = sorted_rain.groupby('Name')['Value'].std().reset_index(name = 'STD_Rain')
med = sorted_rain.groupby('Name')['Value'].median().reset_index(name = "Median_Rain")
AggRain = pd.concat([AggRain, med['Median_Rain']], axis = 1)
AggRain = pd.concat([AggRain, std['STD_Rain']], axis=1)
min = sorted_rain.groupby('Name')['Value'].min().reset_index(name = "Min_Rain")
AggRain = pd.concat([AggRain, min['Min_Rain']], axis = 1)
max = sorted_rain.groupby('Name')['Value'].max().reset_index(name = "Max_Rain")
AggRain = pd.concat([AggRain, max['Max_Rain']], axis = 1)

AggRain

                Name  Mean_Rain   STD_Rain  Min_Rain  Median_Rain
0    Anderson County     45.466  10.556187     35.32        45.23
1     Andrews County      9.704   1.990133      8.33         8.93
2    Angelina County     52.108  14.749668     40.16        48.16
3     Aransas County     32.440  12.634589     22.05        28.36
4      Archer County     28.054   5.111422     22.46        25.93
..               ...        ...        ...       ...          ...
249      Wood County     46.884   7.638506     40.35        44.71
250    Yoakum County     12.886   2.450333     10.00        14.26
251     Young County     28.944   4.778062     23.58        29.65
252    Zapata County     17.434   3.327023     13.44        18.88
253    Zavala County     17.218   3.076292     14.51        16.62

[254 rows x 5 columns]

In [ ]:
AggRain.to_csv('rainfall_cleaned.csv', index = False)