In [ ]:
import pandas as pd
data = pd.read_csv('Unemployment2023 (1).csv')
data_new = data[data['State'] == 'TX']
data_new
data_newest = data_new.copy()
data_newest

,FIPS_Code,State,Area_Name,Attribute,Value
258923,48000,TX,Texas,Unemployed_2000,455364.0
258927,48000,TX,Texas,Unemployed_2001,524310.0
258931,48000,TX,Texas,Unemployed_2002,680965.0
258935,48000,TX,Texas,Unemployed_2003,734082.0
258939,48000,TX,Texas,Unemployed_2004,662144.0
...,...,...,...,...,...
284661,48507,TX,"Zavala County, TX",Unemployed_2021,407.0
284665,48507,TX,"Zavala County, TX",Unemployed_2022,295.0
284669,48507,TX,"Zavala County, TX",Unemployed_2023,254.0
284671,48507,TX,"Zavala County, TX",Median_Household_Income_2022,36237.0
284672,48507,TX,"Zavala County, TX",Med_HH_Income_Percent_of_State_Total_2022,50.1

In [7]:
data_newest.drop(data_newest[data_newest['Area_Name'] == 'Texas'].index, inplace = True)
data_newest

,FIPS_Code,State,Area_Name,Attribute,Value
259019,48001,TX,"Anderson County, TX",Rural_Urban_Continuum_Code_2023,7.0
259020,48001,TX,"Anderson County, TX",Urban_Influence_Code_2013,8.0
259021,48001,TX,"Anderson County, TX",Metro_2023,0.0
259024,48001,TX,"Anderson County, TX",Unemployed_2000,1210.0
259028,48001,TX,"Anderson County, TX",Unemployed_2001,1188.0
...,...,...,...,...,...
284661,48507,TX,"Zavala County, TX",Unemployed_2021,407.0
284665,48507,TX,"Zavala County, TX",Unemployed_2022,295.0
284669,48507,TX,"Zavala County, TX",Unemployed_2023,254.0
284671,48507,TX,"Zavala County, TX",Median_Household_Income_2022,36237.0
284672,48507,TX,"Zavala County, TX",Med_HH_Income_Percent_of_State_Total_2022,50.1

In [26]:
irs_data = pd.read_csv('22incytx.xlsx - Sheet1.csv')
irs_data_newer = pd.DataFrame()
index = 12
for index, val in enumerate(irs_data['Size of adjusted gross income by county']):
    irs_data_newer = pd.concat([irs_data_newer, irs_data.iloc[index]])         
    index += 8

irs_data_newer

,0,1,2,3,4,5,6,7,8,9,...,2541,2542,2543,2544,2545,2546,2547,2548,2549,2550
County \nFIPS \ncode [1],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Size of adjusted gross income by county,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 2,Amount,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
County \nFIPS \ncode [1],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Size of adjusted gross income by county,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Size of adjusted gross income by county,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$100,000 under $200,000",NaN
Unnamed: 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33787,NaN
County \nFIPS \ncode [1],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,507.0
Size of adjusted gross income by county,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$200,000 or more"
Unnamed: 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20711